version: '3.4'

services:

  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres123
    - POSTGRES_DB=logdb
    command: postgres -c 'max_connections=1500'
    ports:
        - '5432:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data
        - ./database.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - proxynet
  logcollector:
    image: ${DOCKER_REGISTRY-}logcollector
    build:
      context: .
      dockerfile: LogCollector/Dockerfile
    networks:
      - proxynet
    depends_on: 
      - postgres_db
volumes:
    postgres_db:
        driver: local
networks:
  proxynet:
    external: false
 

 

